blank_issues_enabled: true
contact_links:
  - name: Peercoin Security Policy
    url: https://github.com/peercoin/peercoin/blob/master/SECURITY.md
    about: View security policy
  - name: Peercoin Community Forum
    url: https://talk.peercoin.net
    about: Peercoin support and community discussions
