#!/usr/bin/env bash
#
#  peercoind The Peercoin server.
#
#
# chkconfig: 345 80 20
# description: peercoind
# processname: peercoind
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/peercoind, see below
if [ -f /etc/sysconfig/peercoind ]; then
        . /etc/sysconfig/peercoind
fi

RETVAL=0

prog=peercoind
# you can override the lockfile via PEERCOIND_LOCKFILE in /etc/sysconfig/peercoind
lockfile=${PEERCOIND_LOCKFILE-/var/lock/subsys/peercoind}

# peercoind defaults to /usr/bin/peercoind, override with PEERCOIND_BIN
peercoind=${PEERCOIND_BIN-/usr/bin/peercoind}

# peercoind opts default to -disablewallet, override with PEERCOIND_OPTS
peercoind_opts=${PEERCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $peercoind $peercoind_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
