description "Peercoin Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env PEERCOIND_BIN="/usr/bin/peercoind"
env PEERCOIND_USER="peercoin"
env PEERCOIND_GROUP="peercoin"
env PEERCOIND_PIDDIR="/var/run/peercoind"
# upstart can't handle variables constructed with other variables
env PEERCOIND_PIDFILE="/var/run/peercoind/peercoind.pid"
env PEERCOIND_CONFIGFILE="/etc/peercoin/peercoin.conf"
env PEERCOIND_DATADIR="/var/lib/peercoind"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # peercoind will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$PEERCOIND_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run peercoind."
        echo "The setting must appear in $PEERCOIND_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Peercoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$PEERCOIND_PIDDIR"
    chmod 0755 "$PEERCOIND_PIDDIR"
    chown $PEERCOIND_USER:$PEERCOIND_GROUP "$PEERCOIND_PIDDIR"
    chown $PEERCOIND_USER:$PEERCOIND_GROUP "$PEERCOIND_CONFIGFILE"
    chmod 0660 "$PEERCOIND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$PEERCOIND_PIDFILE" \
    --chuid $PEERCOIND_USER:$PEERCOIND_GROUP \
    --exec "$PEERCOIND_BIN" \
    -- \
    -pid="$PEERCOIND_PIDFILE" \
    -conf="$PEERCOIND_CONFIGFILE" \
    -datadir="$PEERCOIND_DATADIR" \
    -disablewallet \
    -daemon

